services:
  app:
    build: .
    container_name: leader-election-pecc-2026
    restart: always
    ports:
      - "3000:3000"
    environment:
      # URL koneksi database untuk digunakan oleh Prisma/Lucia/Drizzle di Next.js
      - DATABASE_URL=postgresql://algaray:alfin270206@db:5432/le26-db
      - TOKEN_TUNNEL=${TOKEN_TUNNEL}
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db
  
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    command: tunnel run --token ${TOKEN_TUNNEL}
    restart: unless-stopped
    depends_on:
      - app

  db:
    image: postgres:18-alpine
    container_name: le26_db
    restart: unless-stopped
    ports:
      - "5432:5432" # Membuka akses agar Beekeeper bisa masuk
    environment:
      - POSTGRES_USER=algaray
      - POSTGRES_PASSWORD=alfin270206
      - POSTGRES_DB=le26-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: # Agar data databasemu tidak hilang saat laptop dimatikan