name: Deploy to VPS

on:
  push:
    branches:
      - le26-theme # Jalankan otomatis tiap push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/leader-election-pecc-2026
            git pull origin le26-theme
            docker compose up -d --build
            docker image prune -f